# Makes all programs dependancies.
all: MTOP.out kmlmapper.out

MTOP.out: MTOP.c
	gcc MTOP.c -o MTOP.out

kmlmapper.out: kmlmapper.c
	gcc kmlmapper.c -o kmlmapper.out

clean:
	rm MTOP.out kmlmapper.out
